/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.raven.cell.TableActionCellEditor;
import view.raven.cell.TableActionCellEditorView;
import view.raven.cell.TableActionCellRender;
import view.raven.cell.TableActionCellRenderView;
import view.raven.cell.TableActionEvent;

import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.EventQueue;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.JButton;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JLabel;

/**
 *
 * @author Admin
 */
public class AdminChooseTrain extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
	static AdminChooseTrain frame = new AdminChooseTrain();
    public AdminChooseTrain() {
    	getContentPane().setBackground(new Color(102, 205, 170));
        initComponents();
        TableActionEvent event = new TableActionEvent() {

			@Override
			public void onEdit(int row) {
				System.out.println("Edit row: "+row);
				
			}

			@Override
			public void onDelete(int row) {
				if(table.isEditing()) {
					table.getCellEditor().stopCellEditing();
				}
				DefaultTableModel model = (DefaultTableModel)table.getModel();
				model.removeRow(row);
			}

			@Override
			public void onView(int row) {
				// TODO Auto-generated method stub
				
			}
        	
        };
        table.getColumnModel().getColumn(8).setCellRenderer(new TableActionCellRender());
        table.getColumnModel().getColumn(8).setCellEditor(new TableActionCellEditor(event));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */               
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        table.setSelectionBackground(new Color(0, 250, 154));
        table.setRowHeight(40);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new DefaultTableModel(
        	new Object[][] {
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        	},
        	new String[] {
        		"TransportID", "TrainID", "Tên tàu", "Ga đi", "Ga đến", "Ngày đi", "Số ghế còn trống", "Giá vé", "Action"
        	}
        ) {
        	boolean[] columnEditables = new boolean[] {
        		false, false, false, false, false, false, false, false, true
        	};
        	public boolean isCellEditable(int row, int column) {
        		return columnEditables[column];
        	}
        });
        jScrollPane1.setViewportView(table);
        
        JPanel panel = new JPanel();
        panel.setLayout(null);
        panel.setBackground(new Color(250, 250, 210));
        
        JButton menuHome = new JButton("Trang chủ");
        menuHome.setForeground(new Color(128, 0, 128));
        menuHome.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuHome.setBounds(21, 42, 120, 41);
        panel.add(menuHome);
        menuHome.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				frame.setVisible(false);
				AdminHome.frame.setVisible(true);
			}
		});
        
        JButton menuFind = new JButton("Tìm tàu");
        menuFind.setForeground(new Color(128, 0, 128));
        menuFind.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuFind.setBounds(271, 42, 166, 41);
        panel.add(menuFind);
        menuFind.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				frame.setVisible(false);
				AdminFindTrain.frame.setVisible(true);
			}
		});
        
        JButton menuAdd = new JButton("Thêm chuyến tàu");
        menuAdd.setForeground(new Color(128, 0, 128));
        menuAdd.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuAdd.setBounds(566, 42, 174, 41);
        panel.add(menuAdd);
        menuAdd.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			frame.setVisible(false);
			AdminAddTrain.frame.setVisible(true);
			}
		});
        
        JButton menuLogout = new JButton("Đăng xuất");
        menuLogout.setForeground(new Color(128, 0, 128));
        menuLogout.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuLogout.setBounds(865, 42, 174, 41);
        panel.add(menuLogout);
        menuLogout.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			frame.setVisible(false);
			view.UserLogin.frame.setVisible(true);
			}
		});
        
        JLabel titleChooseTrain = new JLabel("Chọn tàu sửa thông tin\r\n");
        titleChooseTrain.setForeground(new Color(34, 139, 34));
        titleChooseTrain.setFont(new Font("Tahoma", Font.BOLD, 24));
        titleChooseTrain.setBackground(new Color(127, 255, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(122)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 850, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(134, Short.MAX_VALUE))
        		.addComponent(panel, GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(410)
        			.addComponent(titleChooseTrain, GroupLayout.PREFERRED_SIZE, 279, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(417, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(panel, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(titleChooseTrain, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        			.addGap(58)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(114, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
}
