/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.raven.datechooser.*;


import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JButton;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JSeparator;

/**
 *
 * @author raven
 */
public class AdminEditTrain extends JFrame {
	
    /**
     * Creates new form Main
     */
	static AdminEditTrain frame = new AdminEditTrain();
    public AdminEditTrain() {
        initComponents();
        getContentPane().setBackground(new Color(240, 240, 240));
        dateChooser.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser.hidePopup();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new com.raven.datechooser.DateChooser();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        JPanel contentPane = new JPanel();
        contentPane.setLayout(null);
        contentPane.setForeground(new Color(34, 139, 34));
        contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
        contentPane.setBackground(new Color(102, 205, 170));
        
        JPanel panel = new JPanel();
        panel.setLayout(null);
        panel.setBackground(new Color(250, 250, 210));
        panel.setBounds(0, 0, 1096, 116);
        contentPane.add(panel);
        
        JButton menuHome = new JButton("Trang chủ");
        menuHome.setForeground(new Color(128, 0, 128));
        menuHome.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuHome.setBounds(21, 42, 120, 41);
        panel.add(menuHome);
        menuHome.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				frame.setVisible(false);
				AdminHome.frame.setVisible(true);
			}
		});
        
        JButton menuFind = new JButton("Tìm tàu");
        menuFind.setForeground(new Color(128, 0, 128));
        menuFind.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuFind.setBounds(262, 42, 145, 41);
        panel.add(menuFind);
        menuFind.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				frame.setVisible(false);
				AdminFindTrain.frame.setVisible(true);
			}
		});
        
        JButton menuAdd = new JButton("Thêm chuyến tàu");
        menuAdd.setForeground(new Color(128, 0, 128));
        menuAdd.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuAdd.setBounds(567, 42, 174, 41);
        panel.add(menuAdd);
        menuAdd.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			frame.setVisible(false);
			AdminAddTrain.frame.setVisible(true);
			}
		});
        
        JButton menuLogout = new JButton("Đăng xuất");
        menuLogout.setForeground(new Color(128, 0, 128));
        menuLogout.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuLogout.setBounds(882, 42, 174, 41);
        panel.add(menuLogout);
        menuLogout.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			frame.setVisible(false);
			view.UserLogin.frame.setVisible(true);
			}
		});
        
        JLabel titleEdit = new JLabel("Chỉnh sửa thông tin tàu (Admin)");
        titleEdit.setForeground(new Color(34, 139, 34));
        titleEdit.setFont(new Font("Tahoma", Font.BOLD, 26));
        titleEdit.setBackground(new Color(127, 255, 0));
        titleEdit.setBounds(344, 133, 429, 35);
        contentPane.add(titleEdit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(contentPane, GroupLayout.PREFERRED_SIZE, 1094, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(contentPane, GroupLayout.PREFERRED_SIZE, 617, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(136, Short.MAX_VALUE))
        );
        btnDate = new javax.swing.JButton();
        btnDate.setBounds(939, 385, 43, 23);
        contentPane.add(btnDate);
        
                btnDate.setText("...");
                fieldDate = new javax.swing.JTextField();
                fieldDate.setBounds(729, 382, 210, 29);
                contentPane.add(fieldDate);
                
                        dateChooser.setTextRefernce(fieldDate);
                        
                        JLabel lblDate = new JLabel("Ngày đi\r\n");
                        lblDate.setFont(new Font("Tahoma", Font.BOLD, 16));
                        lblDate.setBounds(602, 377, 109, 35);
                        contentPane.add(lblDate);
                        
                        JButton btnEdit = new JButton("Sửa");
                        btnEdit.setFont(new Font("Tahoma", Font.PLAIN, 24));
                        btnEdit.setBounds(435, 503, 239, 45);
                        contentPane.add(btnEdit);
                        
                        JLabel lblTransportID = new JLabel("TransportID:\r\n");
                        lblTransportID.setFont(new Font("Tahoma", Font.BOLD, 16));
                        lblTransportID.setBounds(131, 190, 109, 35);
                        contentPane.add(lblTransportID);
                        
                        JLabel lblTrainName = new JLabel("Tên tàu:");
                        lblTrainName.setFont(new Font("Tahoma", Font.BOLD, 16));
                        lblTrainName.setBounds(131, 257, 86, 35);
                        contentPane.add(lblTrainName);
                        
                        JLabel lblFromStation = new JLabel("Ga đi");
                        lblFromStation.setFont(new Font("Tahoma", Font.BOLD, 16));
                        lblFromStation.setBounds(131, 319, 86, 35);
                        contentPane.add(lblFromStation);
                        
                        JLabel lblPrice = new JLabel("Giá vé:");
                        lblPrice.setFont(new Font("Tahoma", Font.BOLD, 16));
                        lblPrice.setBounds(131, 377, 86, 35);
                        contentPane.add(lblPrice);
                        
                        JLabel lblTrainID = new JLabel("TrainID:");
                        lblTrainID.setFont(new Font("Tahoma", Font.BOLD, 16));
                        lblTrainID.setBounds(602, 190, 109, 35);
                        contentPane.add(lblTrainID);
                        
                        JLabel lblSeats = new JLabel("Ghế còn trống:");
                        lblSeats.setFont(new Font("Tahoma", Font.BOLD, 16));
                        lblSeats.setBounds(602, 257, 124, 35);
                        contentPane.add(lblSeats);
                        
                        JLabel lblToStation = new JLabel("Ga đến:\r\n");
                        lblToStation.setFont(new Font("Tahoma", Font.BOLD, 16));
                        lblToStation.setBounds(602, 319, 109, 35);
                        contentPane.add(lblToStation);
                        
                        fieldTransportID = new JTextField();
                        fieldTransportID.setBounds(265, 190, 210, 29);
                        contentPane.add(fieldTransportID);
                        fieldTransportID.setColumns(10);
                        
                        fieldTrainID = new JTextField();
                        fieldTrainID.setColumns(10);
                        fieldTrainID.setBounds(729, 195, 210, 29);
                        contentPane.add(fieldTrainID);
                        
                        fieldSeats = new JTextField();
                        fieldSeats.setColumns(10);
                        fieldSeats.setBounds(729, 263, 210, 29);
                        contentPane.add(fieldSeats);
                        
                        fieldToStation = new JTextField();
                        fieldToStation.setColumns(10);
                        fieldToStation.setBounds(729, 328, 210, 29);
                        contentPane.add(fieldToStation);
                        
                        fieldTrainName = new JTextField();
                        fieldTrainName.setColumns(10);
                        fieldTrainName.setBounds(265, 263, 210, 29);
                        contentPane.add(fieldTrainName);
                        
                        fieldFromStation = new JTextField();
                        fieldFromStation.setColumns(10);
                        fieldFromStation.setBounds(265, 325, 210, 29);
                        contentPane.add(fieldFromStation);
                        
                        fieldPrice = new JTextField();
                        fieldPrice.setColumns(10);
                        fieldPrice.setBounds(265, 379, 210, 29);
                        contentPane.add(fieldPrice);
                btnDate.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton5ActionPerformed(evt);
                    }
                });
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dateChooser.showPopup();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFindTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFindTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFindTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFindTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.datechooser.DateChooser dateChooser;
    private javax.swing.JButton btnDate;
    private javax.swing.JTextField fieldDate;
    private JTextField fieldTransportID;
    private JTextField fieldTrainID;
    private JTextField fieldSeats;
    private JTextField fieldToStation;
    private JTextField fieldTrainName;
    private JTextField fieldFromStation;
    private JTextField fieldPrice;
}
