/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.raven.datechooser.*;

import view.UserHistory;
import view.UserHome;

import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JButton;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JSeparator;

/**
 *
 * @author raven
 */
public class AdminFindTrain extends JFrame {
	
    /**
     * Creates new form Main
     */
	static AdminFindTrain frame = new AdminFindTrain();
    public AdminFindTrain() {
        initComponents();
        getContentPane().setBackground(new Color(240, 240, 240));
        dateChooser.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser.hidePopup();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new com.raven.datechooser.DateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        JPanel contentPane = new JPanel();
        contentPane.setLayout(null);
        contentPane.setForeground(new Color(34, 139, 34));
        contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
        contentPane.setBackground(new Color(102, 205, 170));
        
        JPanel panel = new JPanel();
        panel.setLayout(null);
        panel.setBackground(new Color(250, 250, 210));
        panel.setBounds(0, 0, 1096, 116);
        contentPane.add(panel);
        
        JButton menuHome = new JButton("Trang chủ");
        menuHome.setForeground(new Color(128, 0, 128));
        menuHome.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuHome.setBounds(21, 42, 120, 41);
        panel.add(menuHome);
        menuHome.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				frame.setVisible(false);
				AdminHome.frame.setVisible(true);
			}
		});
        
        JButton menuFind = new JButton("Tìm tàu");
        menuFind.setForeground(new Color(128, 0, 128));
        menuFind.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuFind.setBounds(262, 42, 145, 41);
        panel.add(menuFind);
        
        JButton menuAdd = new JButton("Thêm chuyến tàu");
        menuAdd.setForeground(new Color(128, 0, 128));
        menuAdd.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuAdd.setBounds(567, 42, 174, 41);
        panel.add(menuAdd);
        menuAdd.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			frame.setVisible(false);
			AdminAddTrain.frame.setVisible(true);
			}
		});
        
        JButton menuLogout = new JButton("Đăng xuất");
        menuLogout.setForeground(new Color(128, 0, 128));
        menuLogout.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuLogout.setBounds(882, 42, 174, 41);
        panel.add(menuLogout);
        menuLogout.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			frame.setVisible(false);
			view.UserLogin.frame.setVisible(true);
			}
		});
        
        JLabel titleFind = new JLabel("Tìm tàu (Admin)");
        titleFind.setForeground(new Color(34, 139, 34));
        titleFind.setFont(new Font("Tahoma", Font.BOLD, 26));
        titleFind.setBackground(new Color(127, 255, 0));
        titleFind.setBounds(413, 130, 239, 35);
        contentPane.add(titleFind);
        
        fieldfromStation = new JTextField();
        fieldfromStation.setColumns(10);
        fieldfromStation.setBounds(357, 253, 340, 35);
        contentPane.add(fieldfromStation);
        
        JLabel lblfromStation = new JLabel("Ga đi:");
        lblfromStation.setFont(new Font("Tahoma", Font.BOLD, 16));
        lblfromStation.setBounds(250, 253, 86, 35);
        contentPane.add(lblfromStation);
        
        JLabel lbltoStation = new JLabel("Ga đến:");
        lbltoStation.setFont(new Font("Tahoma", Font.BOLD, 16));
        lbltoStation.setBounds(250, 327, 86, 35);
        contentPane.add(lbltoStation);
        
        fieldtoStation = new JTextField();
        fieldtoStation.setColumns(10);
        fieldtoStation.setBounds(357, 327, 340, 35);
        contentPane.add(fieldtoStation);
        
        JSeparator separator = new JSeparator();
        separator.setBounds(357, 287, 339, 10);
        contentPane.add(separator);
        
        JSeparator separator_1 = new JSeparator();
        separator_1.setBounds(357, 358, 339, 10);
        contentPane.add(separator_1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(contentPane, GroupLayout.PREFERRED_SIZE, 1094, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(contentPane, GroupLayout.PREFERRED_SIZE, 617, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(136, Short.MAX_VALUE))
        );
        btnDate = new javax.swing.JButton();
        btnDate.setBounds(654, 411, 43, 23);
        contentPane.add(btnDate);
        
                btnDate.setText("...");
                fieldDate = new javax.swing.JTextField();
                fieldDate.setBounds(357, 408, 273, 29);
                contentPane.add(fieldDate);
                
                        dateChooser.setTextRefernce(fieldDate);
                        
                        JLabel lblDate = new JLabel("Ngày đi\r\n");
                        lblDate.setFont(new Font("Tahoma", Font.BOLD, 16));
                        lblDate.setBounds(250, 408, 86, 35);
                        contentPane.add(lblDate);
                        
                        JButton btnFind = new JButton("Tìm");
                        btnFind.setFont(new Font("Tahoma", Font.PLAIN, 24));
                        btnFind.setBounds(435, 503, 239, 45);
                        contentPane.add(btnFind);
                btnDate.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton5ActionPerformed(evt);
                    }
                });
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dateChooser.showPopup();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFindTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFindTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFindTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFindTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.datechooser.DateChooser dateChooser;
    private javax.swing.JButton btnDate;
    private javax.swing.JTextField fieldDate;
    private JTextField fieldfromStation;
    private JTextField fieldtoStation;
}
