/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.raven.cell.TableActionCellEditorView;
import view.raven.cell.TableActionCellRenderView;
import view.raven.cell.TableActionEvent;

import javax.swing.table.DefaultTableModel;


import java.awt.Color;
import java.awt.EventQueue;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.JButton;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JLabel;

import java.util.List;
import java.util.ArrayList;

import model.Train;

/**
 *
 * @author Admin
 */
public class UserChooseTrain extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Test
     */
	static UserChooseTrain frame = new UserChooseTrain();
	private static List<Train> trains = new ArrayList<Train>();
    public UserChooseTrain() {
    	getContentPane().setBackground(new Color(173, 216, 230));
        initComponents();
        TableActionEvent event = new TableActionEvent() {

			@Override
			public void onEdit(int row) {
				
			}

			@Override
			public void onDelete(int row) {
				
			}

			@Override
			public void onView(int row) {
				System.out.println("View row: "+row);
				Train train = trains.get(row);
				Payment.display(train.getTrainID());
			}
        	
        };
        table.getColumnModel().getColumn(6).setCellRenderer(new TableActionCellRenderView());
        table.getColumnModel().getColumn(6).setCellEditor(new TableActionCellEditorView(event));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */               
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        table.setSelectionBackground(new Color(0, 250, 154));
        table.setRowHeight(40);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        table.setModel(new DefaultTableModel(
        	new Object[][] {
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        	},
        	new String[] {
        		"T\u00EAn t\u00E0u", "Ga \u0111i", "Ga \u0111\u1EBFn", "Gi\u1EDD \u0111i", "S\u1ED1 gh\u1EBF tr\u1ED1ng", "Gi\u00E1 v\u00E9", "Action"
        	}
        ) {
        	boolean[] columnEditables = new boolean[] {
        		false, false, false, false, false, false, true
        	};
        	public boolean isCellEditable(int row, int column) {
        		return columnEditables[column];
        	}
        });
		if (trains != null && !trains.isEmpty()) {
			// Xóa dữ liệu hiện tại của bảng
			DefaultTableModel model = (DefaultTableModel) table.getModel();
			model.setRowCount(0);
		
			// Điền dữ liệu từ listTrain vào bảng
			for (Train train : trains) {
				model.addRow(new Object[]{
					train.getTrainName(),
					train.getFromStation(),
					train.getToStation(),
					train.getDate(),
					train.getSeats(),
					train.getPrice(),
					null // Chưa biết bạn muốn thêm gì vào cột Action
				});
			}
		} else {
			// Xóa dữ liệu hiện tại của bảng nếu listTrain rỗng
			DefaultTableModel model = (DefaultTableModel) table.getModel();
			model.setRowCount(0);
		}
        jScrollPane1.setViewportView(table);
        
        JPanel panel = new JPanel();
        panel.setLayout(null);
        panel.setBackground(new Color(250, 250, 210));
        
        JButton menuHome = new JButton("Trang chủ");
        menuHome.setForeground(new Color(128, 0, 128));
        menuHome.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuHome.setBounds(21, 42, 120, 41);
        panel.add(menuHome);
        menuHome.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				frame.setVisible(false);
				UserHome.display();
			}
		});
        
        JButton menuFind = new JButton("Tìm tàu");
        menuFind.setForeground(new Color(128, 0, 128));
        menuFind.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuFind.setBounds(208, 42, 150, 41);
        panel.add(menuFind);
        menuFind.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				frame.setVisible(false);
				UserFindTrain.display();
			}
		});
        
        JButton menuProfile = new JButton("Tài khoản\r\n");
        menuProfile.setForeground(new Color(128, 0, 128));
        menuProfile.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuProfile.setBounds(649, 42, 174, 41);
        panel.add(menuProfile);
        menuProfile.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			frame.setVisible(false);
			UserProfile.display();
			}
		});
        
        JButton menuLogout = new JButton("Đăng xuất");
        menuLogout.setForeground(new Color(128, 0, 128));
        menuLogout.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuLogout.setBounds(871, 42, 174, 41);
        panel.add(menuLogout);
        menuLogout.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			frame.setVisible(false);
			view.UserLogin.frame.setVisible(true);
			}
		});
        
        
        JLabel titleChooseTrain = new JLabel("Chọn tàu\r\n");
        titleChooseTrain.setForeground(new Color(34, 139, 34));
        titleChooseTrain.setFont(new Font("Tahoma", Font.BOLD, 24));
        titleChooseTrain.setBackground(new Color(127, 255, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(122)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 850, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(134, Short.MAX_VALUE))
        		.addComponent(panel, GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(487)
        			.addComponent(titleChooseTrain, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(501, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(panel, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(titleChooseTrain, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        			.addGap(58)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(114, Short.MAX_VALUE))
        );
        
        JButton menuHistory = new JButton("Lịch sử đặt vé\r\n");
        menuHistory.setForeground(new Color(128, 0, 128));
        menuHistory.setFont(new Font("Tahoma", Font.PLAIN, 18));
        menuHistory.setBounds(421, 42, 166, 41);
        panel.add(menuHistory);
        menuHistory.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			frame.setVisible(false);
			UserHistory.frame.setVisible(true);
			}
		});
        
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }                     

    
    public static void display(List<Train> trainsS) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					trains = trainsS;
					frame = new UserChooseTrain();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
}
