/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.test;

import view.com.raven.datechooser.*;

import view.UserFindTrain;
import view.UserHistory;
import view.UserHome;

import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JButton;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JSeparator;

/**
 *
 * @author raven
 */
public class Main extends JFrame {
	
    /**
     * Creates new form Main
     */
	static Main frame = new Main();
    public Main() {
        initComponents();
        getContentPane().setBackground(new Color(240, 240, 240));
        dateChooser.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser.hidePopup();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new view.com.raven.datechooser.DateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        JPanel contentPane = new JPanel();
        contentPane.setLayout(null);
        contentPane.setForeground(new Color(34, 139, 34));
        contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
        contentPane.setBackground(new Color(102, 205, 170));
        
        JPanel panel = new JPanel();
        panel.setLayout(null);
        panel.setBackground(new Color(250, 250, 210));
        panel.setBounds(0, 0, 1096, 116);
        contentPane.add(panel);
        
        JButton btnNewButton = new JButton("Trang chủ");
        btnNewButton.setForeground(new Color(128, 0, 128));
        btnNewButton.setFont(new Font("Tahoma", Font.PLAIN, 18));
        btnNewButton.setBounds(21, 42, 120, 41);
        panel.add(btnNewButton);
        btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				frame.setVisible(false);
				view.UserHome.frame.setVisible(true);
			}
		});
        
        JButton btnngKTi = new JButton("Tìm tàu");
        btnngKTi.setForeground(new Color(128, 0, 128));
        btnngKTi.setFont(new Font("Tahoma", Font.PLAIN, 18));
        btnngKTi.setBounds(224, 42, 110, 41);
        panel.add(btnngKTi);
        
        JButton btnngNhpVi = new JButton("Lịch sử mua vé");
        btnngNhpVi.setForeground(new Color(128, 0, 128));
        btnngNhpVi.setFont(new Font("Tahoma", Font.PLAIN, 18));
        btnngNhpVi.setBounds(420, 42, 174, 41);
        panel.add(btnngNhpVi);
        btnngNhpVi.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			frame.setVisible(false);
			UserHistory.frame.setVisible(true);
			}
		});
        
        JButton btnTiKhon = new JButton("Tài khoản");
        btnTiKhon.setForeground(new Color(128, 0, 128));
        btnTiKhon.setFont(new Font("Tahoma", Font.PLAIN, 18));
        btnTiKhon.setBounds(650, 42, 174, 41);
        panel.add(btnTiKhon);
        btnTiKhon.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			frame.setVisible(false);
			view.UserProfile.frame.setVisible(true);
			}
		});
        
        JButton btnngXut = new JButton("Đăng xuất");
        btnngXut.setForeground(new Color(128, 0, 128));
        btnngXut.setFont(new Font("Tahoma", Font.PLAIN, 18));
        btnngXut.setBounds(882, 42, 174, 41);
        panel.add(btnngXut);
        btnngXut.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			frame.setVisible(false);
			view.UserLogin.frame.setVisible(true);
			}
		});
        
        JLabel lblNewLabel = new JLabel("Tìm vé tàu");
        lblNewLabel.setForeground(new Color(34, 139, 34));
        lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 26));
        lblNewLabel.setBackground(new Color(127, 255, 0));
        lblNewLabel.setBounds(468, 130, 156, 35);
        contentPane.add(lblNewLabel);
        
        textField = new JTextField();
        textField.setColumns(10);
        textField.setBounds(357, 253, 340, 35);
        contentPane.add(textField);
        
        JLabel lblTrainid_2 = new JLabel("Ga đi:");
        lblTrainid_2.setFont(new Font("Tahoma", Font.BOLD, 16));
        lblTrainid_2.setBounds(250, 253, 86, 35);
        contentPane.add(lblTrainid_2);
        
        JLabel lblTrainid_3 = new JLabel("Ga đến:");
        lblTrainid_3.setFont(new Font("Tahoma", Font.BOLD, 16));
        lblTrainid_3.setBounds(250, 327, 86, 35);
        contentPane.add(lblTrainid_3);
        
        textField_1 = new JTextField();
        textField_1.setColumns(10);
        textField_1.setBounds(357, 327, 340, 35);
        contentPane.add(textField_1);
        
        JSeparator separator = new JSeparator();
        separator.setBounds(357, 287, 339, 10);
        contentPane.add(separator);
        
        JSeparator separator_1 = new JSeparator();
        separator_1.setBounds(357, 358, 339, 10);
        contentPane.add(separator_1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(contentPane, GroupLayout.PREFERRED_SIZE, 1094, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(contentPane, GroupLayout.PREFERRED_SIZE, 617, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(136, Short.MAX_VALUE))
        );
        jButton5 = new javax.swing.JButton();
        jButton5.setBounds(654, 411, 43, 23);
        contentPane.add(jButton5);
        
                jButton5.setText("...");
                txtDate1 = new javax.swing.JTextField();
                txtDate1.setBounds(357, 408, 249, 29);
                contentPane.add(txtDate1);
                
                        dateChooser.setTextRefernce(txtDate1);
                        
                        JLabel lblTrainid_3_1 = new JLabel("Ngày đi\r\n");
                        lblTrainid_3_1.setFont(new Font("Tahoma", Font.BOLD, 16));
                        lblTrainid_3_1.setBounds(250, 408, 86, 35);
                        contentPane.add(lblTrainid_3_1);
                        
                        JButton btnNewButton_1 = new JButton("Tìm");
                        btnNewButton_1.setFont(new Font("Tahoma", Font.PLAIN, 24));
                        btnNewButton_1.setBounds(435, 503, 239, 45);
                        contentPane.add(btnNewButton_1);
                jButton5.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton5ActionPerformed(evt);
                    }
                });
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dateChooser.showPopup();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.com.raven.datechooser.DateChooser dateChooser;
    private javax.swing.JButton jButton5;
    private javax.swing.JTextField txtDate1;
    private JTextField textField;
    private JTextField textField_1;
}
